import type { Language } from './types';

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'en-US', name: 'English' },
  { code: 'es-ES', name: 'Spanish' },
  { code: 'fr-FR', name: 'French' },
  { code: 'de-DE', name: 'German' },
  { code: 'it-IT', name: 'Italian' },
  { code: 'ja-JP', name: 'Japanese' },
  { code: 'ko-KR', name: 'Korean' },
  { code: 'pt-BR', name: 'Portuguese' },
  { code: 'ru-RU', name: 'Russian' },
  { code: 'zh-CN', name: 'Chinese (Simplified)' },
  { code: 'hi-IN', name: 'Hindi' },
  { code: 'ar-SA', name: 'Arabic' },

  // 🇮🇳 Indian Languages (22 Scheduled)
  { code: 'as-IN', name: 'Assamese' },
  { code: 'bn-IN', name: 'Bengali' },
  { code: 'brx-IN', name: 'Bodo' },
  { code: 'doi-IN', name: 'Dogri' },
  { code: 'gu-IN', name: 'Gujarati' },
  { code: 'kn-IN', name: 'Kannada' },
  { code: 'ks-IN', name: 'Kashmiri' },
  { code: 'kok-IN', name: 'Konkani' },
  { code: 'mai-IN', name: 'Maithili' },
  { code: 'ml-IN', name: 'Malayalam' },
  { code: 'mni-IN', name: 'Manipuri (Meitei)' },
  { code: 'mr-IN', name: 'Marathi' },
  { code: 'ne-IN', name: 'Nepali' },
  { code: 'or-IN', name: 'Odia' },
  { code: 'pa-IN', name: 'Punjabi' },
  { code: 'sa-IN', name: 'Sanskrit' },
  { code: 'sat-IN', name: 'Santali' },
  { code: 'sd-IN', name: 'Sindhi' },
  { code: 'ta-IN', name: 'Tamil' },
  { code: 'te-IN', name: 'Telugu' },
  { code: 'ur-IN', name: 'Urdu' },
];
